version: "3"
vars:
  K8S_NS: "lan-nanny"
  K8S_NS_DEV: "lan-nanny-dev"
  K8S_NS_STAGE: "lan-nanny-stage"
  K8S_NS_PROD: "lan-nanny"

tasks:
  build-docker:
    cmds:
      - |
        mkdir docker/build-files
        cp -r src docker/build-files
        cp -r tests docker/build-files
        cp pyproject.toml docker/build-files
        cp tox.ini docker/build-files
        docker build -t harbor.squid-ink.us/politeauthority/lan-nanny \
          --build-arg="DOCKER_REGISTRY=harbor.squid-ink.us/docker-hub" \
          --no-cache docker/
        rm -rf docker/build-files
    silent: False
