apiVersion: apps/v1
kind: Deployment
metadata:
  name: lan-nanny-scanner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lan-nanny-scanner
  template:
    metadata:
      labels:
        app: lan-nanny-scanner
    spec:
      imagePullSecrets:
        - name: harbor-registry
      hostNetwork: true
      containers:
        - name: lan-nanny-scanner
          image: harbor.squid-ink.us/politeauthority/lan-nanny:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: LOG_LEVEL
              value: "DEBUG"
            - name: LAN_NANNY_ENV
              value: "DEV"
            - name: LAN_NANNY_API_URL
              valueFrom:
                secretKeyRef:
                  name: lan-nanny-scanner-creds
                  key: API_URL
            - name: LAN_NANNY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: lan-nanny-scanner-creds
                  key: API_KEY
            - name: LAN_NANNY_API_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: lan-nanny-scanner-creds
                  key: API_CLIENT_ID
          resources:
            requests:
              memory: "250Mi"
              cpu: "250m"
            limits:
              memory: "500Mi"
              cpu: "500m"
