#!/bin/bash
# Run the production webserver, which is gunicorn
set -e
APPLICATION_PATH=""

if [ "$LAN_NANNY_ENV" = "dev" ]; then
    APPLICATION_PATH="/work/lan_nanny/src/lan_nanny"
else
    APPLICATION_PATH="/app/lan_nanny"
fi

if [ "$APPLICATION" = "lan-nanny-web" ]; then
    APPLICATION_PATH="${APPLICATION_PATH}/api"
    GUNICORN_APP="web-app:app"
else
    APPLICATION_PATH="${APPLICATION_PATH}/web"
    GUNICORN_APP="api-app:app"
fi


gunicorn ${GUNICORN_APP} --bind 0.0.0.0:80
