apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: lan-nanny
resources:
  - ../../base
  # - secrets.yaml
images:
  - name: harbor.squid-ink.us/politeauthority/lan-nanny
    # newTag: latest
    newTag: 0.0.0.42

patches:
  - target:
      kind: Deployment
      name: lan-nanny-api
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: JWT_EXPIRE_MINUTES
          value: "5760"
  - target:
      kind: Ingress
      name: lan-nanny-api
    patch: |-
      - op: add
        path: /metadata/annotations/cert-manager.io~1cluster-issuer
        value: letsencrypt-prod
      - op: replace
        path: /spec/ingressClassName
        value: nginx-public
      - op: replace
        path: /spec/rules/0/host
        value: api.lan-nanny.alix.lol
      - op: replace
        path: /spec/tls/0/hosts/0
        value: api.lan-nanny.alix.lol
