name: Buil Api Container

on:
  workflow_call:
    inputs:
      tag-prefix:
        required: true
        type: string
      build-target:
        required: true
        type: string

jobs:
  build:
    runs-on: self-hosted
    container:
      image: harbor.squid-ink.us/politeauthority/polite-cicd:${{ vars.CICD_VERSION }}
      credentials:
        username: ${{ vars.HARBOR_USER }}
        password: ${{ secrets.HARBOR_PASSWORD }}
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
      - uses: docker/login-action@v3
        with:
          registry: harbor.squid-ink.us
          username: ${{ vars.HARBOR_USER }}
          password: ${{ secrets.HARBOR_PASSWORD }}
      - name: Build Container
        run: |
          echo "Run Task: Build"
          if [ "$TAG_PREFIX" = "prod" ]; then
            task build-docker -- base
          else
            task build-docker -- dev
          fi
      - name: Push Container
        run: |
          TAG_PREFIX="${{ inputs.tag-prefix }}"

          # Get image
          SEARCH_IMAGE="harbor.squid-ink.us/politeauthority/lan-nanny"
          IMAGE_ID=$(docker images --filter "reference=${SEARCH_IMAGE}" --format "{{.ID}}")

          # Get tag names
          VERSION_FILE="src/lan-nanny/api/version.py"
          VERSION=$(grep -o 'version = "[^"]*"' ${VERSION_FILE} | cut -d '"' -f 2)
          if [ "$TAG_PREFIX" = "prod" ]; then
            TAG_NAMED="latest"
            TAG_VERSION="${VERSION}"
          else
            TAG_NAMED="${TAG_PREFIX}-latest"
            TAG_VERSION="${TAG_PREFIX}-${VERSION}"
          fi

          # Tag
          docker tag ${IMAGE_ID} harbor.squid-ink.us/politeauthority/lan-nanny:${TAG_NAMED}
          docker tag ${IMAGE_ID} harbor.squid-ink.us/politeauthority/lan-nanny:${TAG_VERSION}

          # Push
          docker push harbor.squid-ink.us/politeauthority/lan-nanny:${TAG_NAMED}
          docker push harbor.squid-ink.us/politeauthority/lan-nanny:${TAG_VERSION}

          echo "# Docker Build" >> $GITHUB_STEP_SUMMARY
          echo "**Built:** harbor.squid-ink.us/politeauthority/lan-nanny:${TAG_NAMED}" >> $GITHUB_STEP_SUMMARY
          echo "**Built:** harbor.squid-ink.us/politeauthority/lan-nanny:${TAG_VERSION}" >> $GITHUB_STEP_SUMMARY

# End File: politeauthority/lan-nanny/.github/workflows/build-container.yaml
