name: Push Staging

on:
  push:
    branches: ["stage"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # validate:
  #   uses: ./.github/workflows/validate.yaml
  #   secrets: inherit
  #   permissions:
  #     pull-requests: read
  #     contents: read
  #   with:
  #     cicd-version: "${{ vars.CICD_VERSION }}"
  #     harbor-user: "${{ vars.HARBOR_USER }}"

  build-container:
    needs: [validate]
    uses: ./.github/workflows/build-container.yaml
    secrets: inherit
    permissions:
      pull-requests: read
      contents: read
    with:
      tag-prefix: "stage"
      build-target: "dev"

  # deploy:
  #   runs-on: self-hosted
  #   needs: [build-api]
  #   container:
  #     image: harbor.squid-ink.us/politeauthority/polite-cicd:${{ vars.CICD_VERSION }}
  #     credentials:
  #       username: ${{ vars.HARBOR_USER }}
  #       password: ${{ secrets.HARBOR_PASSWORD }}
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         token: ${{ secrets.PAT }}
  #     - name: Deploy Staging
  #       run: |
  #         mkdir ~/.kube
  #         echo "${{ secrets.KUBECONFIG }}" | base64 -d > ~/.kube/config.yaml
  #         export KUBECONFIG=~/.kube/config.yaml
  #         chmod 600 ~/.kube/config.yaml
  #         task stage-deploy

# End File: politeauthority/lan-nanny.github/workflows/push-staging.yaml
